### ISSUE TITLE
Morning Session Peer-to-peer code review B5D5

### ISSUE THREAD

**Issue by MudasirSherwani** [UsirusenIkon/Allblack-Basketball-Camp-First-Capstone-#3]
### Hi @UsirusenIkon :wave: 
**You have done great efforts to make this project we find that your project is :+1:** 

- [ ] Project Working Fine
- [ ] Nice Design 
- [ ] Linters are Passed 
- [ ] Proper Github flow
- [ ] Professional README file 

**But there is something that needs to improve :dart: we would like to suggest you, please**

- [x]  Update the correct link of your Live demo project link from deployed GitHub pages.
- [x]  Add a video introduction link to your readme file.

**Comment by UsirusenIkon** [comment]
thank you 👋
